---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sop-agent-service
  namespace: cluster-config
spec:
  image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/agent/sop-agent-service
  interval: 1m0s
  secretRef:
    name: ecr-credentials
