apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sop-agent-service
  namespace: agent
spec:
  interval: 1m
  url: https://github.com/dasbraja/agent-unstructured.git
  ref:
    branch: main
  secretRef:
    name: flux-system